merchant-sdk-ruby/samples/config/routes.rb
MerchantSamples::Engine.routes.draw do
  post  "merchant/ipn_notify" => "merchant#ipn_notify", :as => :ipn_notify
  match "merchant(/:action)",  :controller => "merchant", :as => :merchant
  root :to => "merchant#index"
end

merchant-sdk-ruby/samples/app/models/merchant_samples/api_form_builder.rb
module MerchantSamples
  class APIFormBuilder < SimpleForm::FormBuilder
    def fields_for(member_name, member_object = nil, &block)
      member_object ||= ( object.send(member_name) || object.send("#{member_name}=", {}))
      member_options = object.class.members[member_name.to_sym]
      if member_options[:array]
        fields = []
        member_object.each_with_index do |obj, index|
          fields << super(member_name, obj, :index => index, &block)
        end
        fields.join.html_safe
      else
        super(member_name, member_object, &block)
      end
    end
    alias_method :simple_form_for, :fields_for
    alias_method :association, :fields_for

    def input(member_name, options = {})
      super(member_name, api_input_options(member_name, options))
    end

    def api_input_options(member_name, options = {})
      member_options      = object.class.members[member_name.to_sym]
      options[:label]   ||= member_name.to_s.underscore.humanize
      options[:wrapper] ||= :api_sample_form
      options[:required]  = !!member_options[:required] if options[:required].nil?
      if member_options[:type] < PayPal::SDK::Core::API::DataTypes::Enum
        options[:as] = ( member_options[:array] ? :check_boxes : :select )
        options[:collection] = member_options[:type].options
      elsif member_options[:type] == PayPal::SDK::Core::API::DataTypes::SimpleTypes::Boolean
        options[:as] = :select
        options[:collection] = [ true, false ]
      end
      options
    end
  end
end

merchant-sdk-ruby/samples/app/controllers/merchant_samples/application_controller.rb
module MerchantSamples
  class ApplicationController < ActionController::Base

    def default_api_value
      t("#{service_name}.#{service_action}", :default => {})
    end

    def service_name
      params[:controller].gsub(/^.*\//, "")
    end

    def service_action
      params[:action]
    end
    helper_method :service_action, :service_name

  end
end

merchant-sdk-ruby/samples/app/controllers/merchant_samples/merchant_controller.rb
require_dependency "merchant_samples/application_controller"

module MerchantSamples
  class MerchantController < ApplicationController
    include PayPal::SDK::Merchant

    def index
      redirect_to :action => :refund_transaction
    end

    def ipn_notify
      if api.ipn_valid?(request.raw_post)
        logger.info("IPN message: VERIFIED")
        render :text => "VERIFIED"
      else
        logger.info("IPN message: INVALID")
        render :text => "INVALID"
      end
    end

    def refund_transaction
      @refund_transaction = api.build_refund_transaction(params[:RefundTransactionRequestType] || default_api_value)
      @refund_transaction_response = api.refund_transaction(@refund_transaction) if request.post?
    end

    def initiate_recoup
      @initiate_recoup = api.build_initiate_recoup(params[:InitiateRecoupRequestType] || default_api_value)
      @initiate_recoup_response = api.initiate_recoup(@initiate_recoup) if request.post?
    end

    def complete_recoup
      @complete_recoup = api.build_complete_recoup(params[:CompleteRecoupRequestType] || default_api_value)
      @complete_recoup_response = api.complete_recoup(@complete_recoup) if request.post?
    end

    def cancel_recoup
      @cancel_recoup = api.build_cancel_recoup(params[:CancelRecoupRequestType] || default_api_value)
      @cancel_recoup_response = api.cancel_recoup(@cancel_recoup) if request.post?
    end

    def get_transaction_details
      @get_transaction_details = api.build_get_transaction_details(params[:GetTransactionDetailsRequestType] || default_api_value)
      @get_transaction_details_response = api.get_transaction_details(@get_transaction_details) if request.post?
    end

    def bm_create_button
      @bm_create_button = api.build_bm_create_button(params[:BMCreateButtonRequestType] || default_api_value)
      @bm_create_button_response = api.bm_create_button(@bm_create_button) if request.post?
    end

    def bm_update_button
      @bm_update_button = api.build_bm_update_button(params[:BMUpdateButtonRequestType] || default_api_value)
      @bm_update_button_response = api.bm_update_button(@bm_update_button) if request.post?
    end

    def bm_manage_button_status
      @bm_manage_button_status = api.build_bm_manage_button_status(params[:BMManageButtonStatusRequestType] || default_api_value)
      @bm_manage_button_status_response = api.bm_manage_button_status(@bm_manage_button_status) if request.post?
    end

    def bm_get_button_details
      @bm_get_button_details = api.build_bm_get_button_details(params[:BMGetButtonDetailsRequestType] || default_api_value)
      @bm_get_button_details_response = api.bm_get_button_details(@bm_get_button_details) if request.post?
    end

    def bm_set_inventory
      @bm_set_inventory = api.build_bm_set_inventory(params[:BMSetInventoryRequestType] || default_api_value)
      @bm_set_inventory_response = api.bm_set_inventory(@bm_set_inventory) if request.post?
    end

    def bm_get_inventory
      @bm_get_inventory = api.build_bm_get_inventory(params[:BMGetInventoryRequestType] || default_api_value)
      @bm_get_inventory_response = api.bm_get_inventory(@bm_get_inventory) if request.post?
    end

    def bm_button_search
      @bm_button_search = api.build_bm_button_search(params[:BMButtonSearchRequestType] || default_api_value)
      @bm_button_search_response = api.bm_button_search(@bm_button_search) if request.post?
    end

    def bill_user
      @bill_user = api.build_bill_user(params[:BillUserRequestType] || default_api_value)
      @bill_user_response = api.bill_user(@bill_user) if request.post?
    end

    def transaction_search
      @transaction_search = api.build_transaction_search(params[:TransactionSearchRequestType] || default_api_value)
      @transaction_search_response = api.transaction_search(@transaction_search) if request.post?
    end

    def mass_pay
      @mass_pay = api.build_mass_pay(params[:MassPayRequestType] || default_api_value)
      @mass_pay_response = api.mass_pay(@mass_pay) if request.post?
    end

    def bill_agreement_update
      @bill_agreement_update = api.build_bill_agreement_update(params[:BillAgreementUpdateRequestType] || default_api_value)
      @bill_agreement_update_response = api.bill_agreement_update(@bill_agreement_update) if request.post?
    end

    def address_verify
      @address_verify = api.build_address_verify(params[:AddressVerifyRequestType] || default_api_value)
      @address_verify_response = api.address_verify(@address_verify) if request.post?
    end

    def enter_boarding
      @enter_boarding = api.build_enter_boarding(params[:EnterBoardingRequestType] || default_api_value)
      @enter_boarding_response = api.enter_boarding(@enter_boarding) if request.post?
    end

    def get_boarding_details
      @get_boarding_details = api.build_get_boarding_details(params[:GetBoardingDetailsRequestType] || default_api_value)
      @get_boarding_details_response = api.get_boarding_details(@get_boarding_details) if request.post?
    end

    def create_mobile_payment
      @create_mobile_payment = api.build_create_mobile_payment(params[:CreateMobilePaymentRequestType] || default_api_value)
      @create_mobile_payment_response = api.create_mobile_payment(@create_mobile_payment) if request.post?
    end

    def get_mobile_status
      @get_mobile_status = api.build_get_mobile_status(params[:GetMobileStatusRequestType] || default_api_value)
      @get_mobile_status_response = api.get_mobile_status(@get_mobile_status) if request.post?
    end

    def set_mobile_checkout
      @set_mobile_checkout = api.build_set_mobile_checkout(params[:SetMobileCheckoutRequestType] || default_api_value)
      @set_mobile_checkout_response = api.set_mobile_checkout(@set_mobile_checkout) if request.post?
    end

    def do_mobile_checkout_payment
      @do_mobile_checkout_payment = api.build_do_mobile_checkout_payment(params[:DoMobileCheckoutPaymentRequestType] || default_api_value)
      @do_mobile_checkout_payment_response = api.do_mobile_checkout_payment(@do_mobile_checkout_payment) if request.post?
    end

    def get_balance
      @get_balance = api.build_get_balance(params[:GetBalanceRequestType] || default_api_value)
      @get_balance_response = api.get_balance(@get_balance) if request.post?
    end

    def get_pal_details
      @get_pal_details = api.build_get_pal_details(params[:GetPalDetailsRequestType] || default_api_value)
      @get_pal_details_response = api.get_pal_details(@get_pal_details) if request.post?
    end

    def do_express_checkout_payment
      @do_express_checkout_payment = api.build_do_express_checkout_payment(params[:DoExpressCheckoutPaymentRequestType] || default_api_value)
      details = @do_express_checkout_payment.DoExpressCheckoutPaymentRequestDetails
      details.Token   = params[:token]    if params[:token]
      details.PayerID = params[:PayerID]  if params[:PayerID]
      details.PaymentDetails[0].NotifyURL ||= ipn_notify_url
      @do_express_checkout_payment_response = api.do_express_checkout_payment(@do_express_checkout_payment) if request.post?
    end

    def do_uatp_express_checkout_payment
      @do_uatp_express_checkout_payment = api.build_do_uatp_express_checkout_payment(params[:DoUATPExpressCheckoutPaymentRequestType] || default_api_value)
      @do_uatp_express_checkout_payment_response = api.do_uatp_express_checkout_payment(@do_uatp_express_checkout_payment) if request.post?
    end

    def set_auth_flow_param
      @set_auth_flow_param = api.build_set_auth_flow_param(params[:SetAuthFlowParamRequestType] || default_api_value)
      @set_auth_flow_param_response = api.set_auth_flow_param(@set_auth_flow_param) if request.post?
    end

    def get_auth_details
      @get_auth_details = api.build_get_auth_details(params[:GetAuthDetailsRequestType] || default_api_value)
      @get_auth_details_response = api.get_auth_details(@get_auth_details) if request.post?
    end

    def set_access_permissions
      @set_access_permissions = api.build_set_access_permissions(params[:SetAccessPermissionsRequestType] || default_api_value)
      @set_access_permissions_response = api.set_access_permissions(@set_access_permissions) if request.post?
    end

    def update_access_permissions
      @update_access_permissions = api.build_update_access_permissions(params[:UpdateAccessPermissionsRequestType] || default_api_value)
      @update_access_permissions_response = api.update_access_permissions(@update_access_permissions) if request.post?
    end

    def get_access_permission_details
      @get_access_permission_details = api.build_get_access_permission_details(params[:GetAccessPermissionDetailsRequestType] || default_api_value)
      @get_access_permission_details_response = api.get_access_permission_details(@get_access_permission_details) if request.post?
    end

    def get_incentive_evaluation
      @get_incentive_evaluation = api.build_get_incentive_evaluation(params[:GetIncentiveEvaluationRequestType] || default_api_value)
      @get_incentive_evaluation_response = api.get_incentive_evaluation(@get_incentive_evaluation) if request.post?
    end

    def set_express_checkout
      @set_express_checkout = api.build_set_express_checkout(params[:SetExpressCheckoutRequestType] || default_api_value)

      # Find Item Total and Order Total
      details = @set_express_checkout.SetExpressCheckoutRequestDetails
      pay = details.PaymentDetails[0]
      pay.ItemTotal  = pay.PaymentDetailsItem[0].Amount
      pay.OrderTotal.currencyID = pay.ItemTotal.currencyID
      pay.OrderTotal.value = pay.ItemTotal.value.to_f + pay.ShippingTotal.value.to_f

      # Notify url
      pay.NotifyURL ||= ipn_notify_url

      # Return and cancel url
      details.ReturnURL ||= merchant_url(:do_express_checkout_payment)
      details.CancelURL ||= merchant_url(:set_express_checkout)

      @set_express_checkout_response = api.set_express_checkout(@set_express_checkout) if request.post?
    end

merchant-sdk-ruby/samples/app/helpers/merchant_samples/application_helper.rb
module MerchantSamples
  module ApplicationHelper
    def active_li(display, link_path, options = {})
      active_menu = options.delete(:match_path) ? request.path =~ Regexp.new(link_path) : request.path == link_path
      content_tag(:li, :class => active_menu ? "active" : "") do
        link_to(display, link_path, options)
      end
    end

    def active_li_regexp(display, link_path, options = {})
      active_li(display, link_path, options.merge(:match_path => true))
    end

    def api_form_for(object, *args, &block)
      options         = args.extract_options!
      options[:as]  ||= api_class_name(object.class)
      simple_form_for(object, *(args << options.merge(:builder => APIFormBuilder, :wrapper => :api_sample_form)), &block)
    end

    def generate_code(api_request, api_response)
      request_hash= api_request.to_hash(:namespace => false, :attribute => false)
      request_hash.delete("Version")
      # request_hash  = get_dotted_hash(request_hash)
      response_hash = api_response.to_hash(:namespace => false, :attribute => false)
      ruby_code   = render("ruby_code.rb", :api_request => api_request, :api_response => api_response,
                       :request_hash => request_hash, :response_hash => response_hash)
      ruby_code.html_safe
    end

    def get_dotted_hash(hash, prefix = "", values = {})
      max_lenght  = Hash[hash.select{|k, v| !(v.is_a? Hash or v.is_a? Array) }].keys.map(&:size).max
      hash.each do |key, value|
        if value.is_a? Hash
          get_dotted_hash(value, "#{prefix}#{key}.", values)
        elsif value.is_a? Array and value[0].is_a? Hash
          value.each_with_index do |array_value, index|
            get_dotted_hash(array_value, "#{prefix}#{key}[#{index}].", values)
          end
        elsif !value.nil?
          k = sprintf("%s%-#{max_lenght}s", prefix, key)
          values[k] = value
        end
      end
      values
    end

    def format_hash(hash)
      entries = hash.map do |key, value|
        "#{key.to_sym.inspect} => " +
          if value.is_a? Hash and value.size > 0
            format_hash(value)
          elsif value.is_a? Array and value[0].is_a? Hash
            "[" + value.map{|v| format_hash(v) }.join(",") + "]"
          else
            value.to_json
          end
      end
      indent_hash_entries(entries)
    end

    def indent_hash_entries(entries)
      if entries.size > 0
        "{\n" + entries.join(",\n").gsub(/^/, "  ") + " }"
      else
        "{}"
      end
    end

    def api_class_name(klass)
      klass.name.gsub(/^.*::/, "")
    end
  end
end

merchant-sdk-ruby/samples/app/helpers/merchant_samples/merchant_helper.rb
module MerchantSamples
  module MerchantHelper
  end
end

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/_address.html.haml
= f.input :Name
= f.input :Street1
= f.input :Street2
= f.input :CityName
= f.input :StateOrProvince
= f.input :PostalCode
= f.input :Country

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/_amount.html.haml
= f.input :currencyID
= f.input :value

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/address_verify.html.haml
= api_form_for @address_verify, :url => merchant_path(:address_verify) do |f|
  .row
    .span5
      %legend Address verify request
      = f.input :Email
      = f.input :Street
      = f.input :Zip

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @address_verify_response
  = render 'api_response', :request => @address_verify, :response => @address_verify_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/bill_agreement_update.html.haml
= api_form_for @bill_agreement_update, :url => merchant_path(:bill_agreement_update) do |f|
  .row
    .span10
      %legend Bill agreement update request
      = f.input :ReferenceID
      = f.input :BillingAgreementStatus
      = f.input :BillingAgreementDescription

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bill_agreement_update_response
  = render 'api_response', :request => @bill_agreement_update, :response => @bill_agreement_update_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/bill_outstanding_amount.html.haml
= api_form_for @bill_outstanding_amount, :url => merchant_path(:bill_outstanding_amount) do |f|
  .row
    .span10
      %legend Bill outstanding amount request
      = f.fields_for :BillOutstandingAmountRequestDetails do |detail|
        = detail.input :ProfileID
        = detail.fields_for :Amount do |amt|
          = render "amount", :f => amt

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @bill_outstanding_amount_response
  = render 'api_response', :request => @bill_outstanding_amount, :response => @bill_outstanding_amount_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/do_non_referenced_credit.html.haml
= api_form_for @do_non_referenced_credit, :url => merchant_path(:do_non_referenced_credit) do |f|

  = f.fields_for :DoNonReferencedCreditRequestDetails do |det|
    .row
      .span5
        %legend Do non referenced credit request
        = det.fields_for :CreditCard do |cc|
          = render 'credit_card', :f => cc
      .span5
        %legend Net Amount
        = det.fields_for :NetAmount do |amt|
          = render 'amount', :f => amt
        = det.input :Comment

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @do_non_referenced_credit_response
  = render 'api_response', :request => @do_non_referenced_credit, :response => @do_non_referenced_credit_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/enter_boarding.html.haml
= api_form_for @enter_boarding, :url => merchant_path(:enter_boarding) do |f|
  = f.fields_for :EnterBoardingRequestDetails do |det|
    .row
      .span5
        %legend Enter boarding request
        = det.input :ProgramCode
        = det.input :ProductList
        %legend Business Info
        = det.fields_for :BusinessInfo do |business|
          = business.input :Name
          = business.input :Type
          = business.input :Category
          = business.input :AverageMonthlyVolume
          = business.input :AveragePrice
          = business.input :RevenueFromOnlineSales
        = det.input :MarketingCategory
      .span5
        %legend Owner Info
        = det.fields_for :OwnerInfo do |owner_info|
          = owner_info.fields_for :Owner do |owner|
            = owner.fields_for :PayerName do |name|
              = name.input :FirstName
              = name.input :LastName
          = owner_info.input :MobilePhone
          = owner_info.input :SSN

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @enter_boarding_response
  = render 'api_response', :request => @enter_boarding, :response => @enter_boarding_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/get_billing_agreement_customer_details.html.haml
= api_form_for @get_billing_agreement_customer_details, :url => merchant_path(:get_billing_agreement_customer_details) do |f|
  .row
    .span10
      %legend Get billing agreement customer details request
      = f.input :Token

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_billing_agreement_customer_details_response
  = render 'api_response', :request => @get_billing_agreement_customer_details, :response => @get_billing_agreement_customer_details_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/get_boarding_details.html.haml
= api_form_for @get_boarding_details, :url => merchant_path(:get_boarding_details) do |f|
  .row
    .span5
      %legend Get boarding request
      = f.input :Token

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_boarding_details_response
  = render 'api_response', :request => @get_boarding_details, :response => @get_boarding_details_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/get_express_checkout_details.html.haml
= api_form_for @get_express_checkout_details, :url => merchant_path(:get_express_checkout_details) do |f|
  .row
    .span5
      %legend Get express checkout
      = f.input :Token

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_express_checkout_details_response
  = render 'api_response', :request => @get_express_checkout_details, :response => @get_express_checkout_details_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/get_pal_details.html.haml
= api_form_for @get_pal_details, :url => merchant_path(:get_pal_details) do |f|
  .row
    .span5
      %legend Get pal details request
      %p No parameters required. Just click `Submit`

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_pal_details_response
  = render 'api_response', :request => @get_pal_details, :response => @get_pal_details_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/get_transaction_details.html.haml
= api_form_for @get_transaction_details, :url => merchant_path(:get_transaction_details) do |f|

  .row
    .span5
      %legend Get transaction details request
      = f.input :TransactionID

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @get_transaction_details_response
  = render 'api_response', :request => @get_transaction_details, :response => @get_transaction_details_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/refund_transaction.html.haml
= api_form_for @refund_transaction, :url => merchant_path(:refund_transaction) do |f|

  .row
    .span5
      %legend Refund transaction request
      = f.input :TransactionID
      = f.input :RefundType
      = f.input :RefundSource
    .span5
      %legend Amount
      = f.fields_for :Amount do |amount|
        = amount.input :currencyID
        = amount.input :value

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @refund_transaction_response
  = render 'api_response', :request => @refund_transaction, :response => @refund_transaction_response

merchant-sdk-ruby/samples/app/views/merchant_samples/merchant/transaction_search.html.haml
= api_form_for @transaction_search, :url => merchant_path(:transaction_search) do |f|

  .row
    .span5
      %legend transaction search request
      = f.input :StartDate
      = f.input :EndDate
      = f.input :TransactionID
      = f.input :Status
      = f.input :TransactionClass

  .form-actions
    = f.submit "Submit", :class => "btn btn-primary", :data => { :disable_with => "Processing.." }

- if @transaction_search_response
  = render 'api_response', :request => @transaction_search, :response => @transaction_search_response